/**
 * Lightweight structural extraction over the current server's monster .lua
 * files. Not a full Lua parser -- these files are machine-generated by a
 * small, consistent set of tools, so anchored regex + brace balancing is
 * enough. Used only to READ specific fields/blocks; files are never
 * rewritten by reformatting what this module parses (untouched files are
 * always copied verbatim, touched ones are edited by text splice, never
 * fully regenerated from this structure).
 */
'use strict';
const fs = require('fs');

// Extracts monster.name (or falls back to Game.createMonsterType("...")).
function extractName(text) {
  const m = /^monster\.name\s*=\s*"((?:[^"\\]|\\.)*)"/m.exec(text);
  if (m) return m[1];
  const m2 = /Game\.createMonsterType\("((?:[^"\\]|\\.)*)"\)/.exec(text);
  return m2 ? m2[1] : null;
}

function extractRaceId(text) {
  const m = /^monster\.raceId\s*=\s*(\d+)/m.exec(text);
  return m ? Number(m[1]) : null;
}

// Finds `monster.<field> = {` and returns the balanced-brace block text
// (including the outer braces), or null if the field isn't present.
function extractBlock(text, field) {
  const anchorRe = new RegExp(`monster\\.${field}\\s*=\\s*\\{`);
  const anchor = anchorRe.exec(text);
  if (!anchor) return null;

  let depth = 0;
  let start = anchor.index + anchor[0].length - 1; // position of the opening '{'
  for (let i = start; i < text.length; i++) {
    const c = text[i];
    if (c === '{') depth++;
    else if (c === '}') {
      depth--;
      if (depth === 0) {
        return { text: text.slice(start, i + 1), start, end: i + 1, matchStart: anchor.index };
      }
    }
  }
  return null; // unbalanced -- caller should treat as "not found" and flag for manual review
}

function extractMonsterInfo(filePath) {
  const text = fs.readFileSync(filePath, 'utf8');
  return {
    filePath,
    text,
    name: extractName(text),
    raceId: extractRaceId(text),
    hasBestiary: /monster\.Bestiary\s*=\s*\{/.test(text),
    hasVoices: extractBlock(text, 'voices') !== null,
    hasSummon: extractBlock(text, 'summon') !== null,
  };
}

module.exports = { extractName, extractRaceId, extractBlock, extractMonsterInfo };
